import { Amplify } from 'aws-amplify';
// amplify_outputs.json is generated by:
//   cd investorsplaygroundbackend && npx ampx generate outputs --branch main --out-dir ../investorsplaygroundweb
import outputs from '../../amplify_outputs.json';

Amplify.configure(outputs as Parameters<typeof Amplify.configure>[0]);
